Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g33, pull requests merged in 2022-09, with the labels that each got.

#50 Add HTTP Gateway
  gateway/Dockerfile
  gateway/makefile
  gateway/scripts/build-golang-app.sh
  gateway/scripts/build-image.sh
  gateway/scripts/build-script.sh
  gateway/scripts/run-container.sh
  gateway/service_definitions.yaml
  gateway/src/env_loader.go
  gateway/src/gateway/matching-service.pb.go
  gateway/src/gateway/matching-service.pb.gw.go
  gateway/src/gateway/matching-service_grpc.pb.go
  gateway/src/gateway/types.pb.go
  gateway/src/gateway/user-bff-service.pb.go
  gateway/src/gateway/user-bff-service.pb.gw.go
  gateway/src/gateway/user-bff-service_grpc.pb.go
  gateway/src/gateway/user-service.pb.go
  gateway/src/gateway/user-service_grpc.pb.go
  gateway/src/go.mod
  gateway/src/go.sum
  gateway/src/main.go
  gateway/src/makefile
  package.json
  proto/matching-service.proto
  proto/types.proto
  proto/user-bff-service.proto
  proto/user-service.proto
  scripts/gen-gateway.sh
Labels: Type/Feature

#49 Add Redis-Based JWT Blacklisting
  user-service/.env.sample
  user-service/.eslintignore
  user-service/package-lock.json
  user-service/package.json
  user-service/src/auth/authentication_agent.ts
  user-service/src/auth/authentication_agent_types.d.ts
  user-service/src/auth/token_blacklist.ts
  user-service/src/index.ts
  user-service/src/redis_adapter/redis_auth_adapter.ts
  user-service/src/utils/env_loader.ts
  user-service/tsconfig.json
Labels: Type/Enhancement

#48 Add Matchmaking Queueing
  .github/workflows/ci-tests.yml
  .gitignore
  config_env/matching-service.env.sample
  config_env/matchmaker.env.sample
  docker-compose.yml
  frontend/src/proto/matching-service.ts
  gateway/scripts/run-container.sh
  images/redis.dockerfile
  matching-service/.env.sample
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/src/controller/matching_service_controller.ts
  matching-service/src/controller/matching_service_handlers/check_status_handler.ts
  matching-service/src/controller/matching_service_handlers/join_queue_handler.ts
  matching-service/src/index.ts
  matching-service/src/proto/matching-service.ts
  matching-service/src/redis/redis_adapter.ts
  matching-service/src/utils/env_loader.ts
  matching-service/tsconfig.json
  matchmaker/Dockerfile
  matchmaker/README.md
  matchmaker/makefile
  matchmaker/scripts/build-golang-app.sh
  matchmaker/scripts/build-image.sh
  matchmaker/scripts/build-script.sh
  matchmaker/scripts/run-container.sh
  matchmaker/src/common/types.go
  matchmaker/src/conn/redis_client.go
  matchmaker/src/conn/redis_client_test.go
  matchmaker/src/env_loader.go
  matchmaker/src/go.mod
  matchmaker/src/go.sum
  matchmaker/src/main.go
  matchmaker/src/makefile
  matchmaker/src/mocks/mock_redis_client.go
  matchmaker/src/worker/fetch_worker.go
  matchmaker/src/worker/fetch_worker_test.go
  matchmaker/src/worker/match_worker.go
  matchmaker/src/worker/match_worker_test.go
  proto/matching-service.proto
  user-service/src/proto/matching-service.ts
Labels: Type/Feature

#46 Add Queue UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/app/store.ts
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/components/auth/UnprotectedRoute.tsx
  frontend/src/components/form/QueueForm.tsx
  frontend/src/components/form/TempQueueForm.tsx
  frontend/src/components/matching/Countdown.tsx
  frontend/src/components/matching/CountdownText.tsx
  frontend/src/components/ui/Navbar.tsx
  frontend/src/feature/matching/matchingSlice.ts
  frontend/src/feature/user/userSlice.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/Session.tsx
Labels: Type/Feature

#52 Add Redis-Based JWT blacklist to matching service
  matching-service/src/auth/authentication_agent.ts
  matching-service/src/auth/authentication_agent_types.d.ts
  matching-service/src/auth/token_blacklist.ts
  matching-service/src/controller/matching_service_controller.ts
  matching-service/src/controller/matching_service_handlers/check_status_handler.ts
  matching-service/src/controller/matching_service_handlers/join_queue_handler.ts
  matching-service/src/index.ts
  matching-service/src/redis_adapter/redis_auth_adapter.ts
  matching-service/src/redis_adapter/redis_matching_adapter.ts
Labels: Module/Back-End, Type/Bug-Fix

#54 Update Gateway
  collab-service/src/utils/env_loader.ts
  docker-compose.yml
  gateway/src/gateway/collab-service.pb.go
  gateway/src/gateway/collab-service_grpc.pb.go
  gateway/src/gateway/matching-service.pb.go
  gateway/src/main.go
  matching-service/src/utils/env_loader.ts
Labels: Type/Bug-Fix

#55 Hotfix Protobuf Packaging Issue
  gateway/src/gateway/collab-service.pb.go
  gateway/src/gateway/collab-service_grpc.pb.go
  proto/collab-service.proto
Labels: Type/Bug-Fix

#56 Fix GRPC routing in matching service
  matching-service/src/controller/matching_service_controller.ts
Labels: Type/Bug-Fix

#57 Add CORS to Gateway and Improve CI
  .github/workflows/ci-build.yml
  .github/workflows/ci-tests.yml
  gateway/src/go.mod
  gateway/src/go.sum
  gateway/src/main.go
Labels: Type/Enhancement

#58 Queue UI integration
  .gitignore
  docker-compose.yml
  frontend/src/App.tsx
  frontend/src/axios.ts
  frontend/src/components/form/TempQueueForm.tsx
  frontend/src/components/matching/Countdown.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  gateway/scripts/build-golang-app.sh
  gateway/scripts/build-image.sh
Labels: Type/Feature

#60 Add Websocket Proxy
  config_env/gateway.env.sample
  config_env/matching-service.env.sample
  config_env/user-service.env.sample
  docker-compose.yml
  gateway/src/env_loader.go
  gateway/src/gateway/tunnel-service.pb.go
  gateway/src/gateway/tunnel-service_grpc.pb.go
  gateway/src/gateway_main.go
  gateway/src/go.mod
  gateway/src/go.sum
  gateway/src/main.go
  gateway/src/proxy/grpc_proxy_client.go
  gateway/src/proxy/ws_proxy_manager.go
  gateway/src/proxy_main.go
  proto/tunnel-service.proto
  tunnel-placeholder/Dockerfile
  tunnel-placeholder/makefile
  tunnel-placeholder/scripts/build-golang-app.sh
  tunnel-placeholder/scripts/build-image.sh
  tunnel-placeholder/scripts/build-script.sh
  tunnel-placeholder/scripts/run-container.sh
  tunnel-placeholder/src/go.mod
  tunnel-placeholder/src/go.sum
  tunnel-placeholder/src/main.go
  tunnel-placeholder/src/makefile
  tunnel-placeholder/src/proto/tunnel-service.pb.go
  tunnel-placeholder/src/proto/tunnel-service_grpc.pb.go
Labels: Type/Feature

#89 Collaboration UI skeleton
  frontend/src/components/editor/EditorTabs.tsx
  frontend/src/components/ui/navbar/HomeNavbar.tsx
  frontend/src/components/ui/navbar/SessionNavbar.tsx
  frontend/src/constants.ts
  frontend/src/feature/matching/matchingSlice.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/InvalidSession.tsx
  frontend/src/pages/Session.tsx
Labels: Module/Front-End

#88 Add Session Management Service
  .github/workflows/ci-build.yml
  .github/workflows/ci-tests.yml
  config_env/session-service.env
  config_env/session-service.env.sample
  docker-compose.yml
  package.json
  proto/session-service.proto
  scripts/gen-proto-go.sh
  session-service/Dockerfile
  session-service/makefile
  session-service/scripts/build-golang-app.sh
  session-service/scripts/build-image.sh
  session-service/scripts/build-script.sh
  session-service/scripts/run-container.sh
  session-service/src/conn/redis_client.go
  session-service/src/conn/redis_client_test.go
  session-service/src/env_loader.go
  session-service/src/go.mod
  session-service/src/go.sum
  session-service/src/main.go
  session-service/src/makefile
  session-service/src/mocks/mock_clock.go
  session-service/src/mocks/mock_redis_client.go
  session-service/src/mocks/mock_token_blacklist.go
  session-service/src/proto/session-service.pb.go
  session-service/src/proto/session-service_grpc.pb.go
  session-service/src/server/server.go
  session-service/src/server/server_interfaces.go
  session-service/src/service/handlers/add_blacklist_handler.go
  session-service/src/service/handlers/create_token_handler.go
  session-service/src/service/handlers/validate_token_handler.go
  session-service/src/service/session_service_server.go
  session-service/src/token/jwt_agent.go
  session-service/src/token/jwt_agent_test.go
  session-service/src/token/token.go
  session-service/src/token/token_agent.go
  session-service/src/token/token_agent_test.go
  session-service/src/token/token_blacklist.go
  session-service/src/token/token_errors.go
  session-service/src/util/clock.go
Labels: Type/Feature

#90 Improve Protobuf Generation
  .gitattributes
  collab-service/proto-emit.cfg
  collab-service/src/proto/matching-service.grpc-client.ts
  collab-service/src/proto/matching-service.grpc-server.ts
  collab-service/src/proto/matching-service.ts
  collab-service/src/proto/user-bff-service.grpc-client.ts
  collab-service/src/proto/user-bff-service.grpc-server.ts
  collab-service/src/proto/user-bff-service.ts
  db/proto
  db/proto-emit.cfg
  frontend/proto-emit.cfg
  frontend/src/proto/collab-service.grpc-client.ts
  frontend/src/proto/collab-service.grpc-server.ts
  frontend/src/proto/collab-service.ts
  frontend/src/proto/user-service.grpc-client.ts
  frontend/src/proto/user-service.grpc-server.ts
  frontend/src/proto/user-service.ts
  matching-service/proto-emit.cfg
  matching-service/src/proto/collab-service.grpc-client.ts
  matching-service/src/proto/collab-service.grpc-server.ts
  matching-service/src/proto/collab-service.ts
  matching-service/src/proto/user-bff-service.grpc-client.ts
  matching-service/src/proto/user-bff-service.grpc-server.ts
  matching-service/src/proto/user-bff-service.ts
  matching-service/src/proto/user-service.grpc-client.ts
  matching-service/src/proto/user-service.grpc-server.ts
  matching-service/src/proto/user-service.ts
  package.json
  scripts/gen-proto.sh
  user-service/proto-emit.cfg
  user-service/src/proto/collab-service.grpc-client.ts
  user-service/src/proto/collab-service.grpc-server.ts
  user-service/src/proto/collab-service.ts
  user-service/src/proto/matching-service.grpc-client.ts
  user-service/src/proto/matching-service.grpc-server.ts
  user-service/src/proto/matching-service.ts
Labels: Type/Enhancement

#92 Remove Session Service Environment File
  .gitignore
  config_env/session-service.env
Labels: Type/Bug-Fix

#98 Prefix API routes with api
  frontend/src/components/form/TempQueueForm.tsx
  frontend/src/components/matching/Countdown.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/Session.tsx
  gateway/service_definitions.yaml
  gateway/src/auth/auth_mux.go
  gateway/src/main.go
  gateway/src/middleware_prefix_router.go
  gateway/src/middleware_proxy.go
  gateway/src/middleware_static.go
  gateway/src/proto/matching-service.pb.gw.go
  gateway/src/proto/user-bff-service.pb.gw.go
Labels: Type/Enhancement, Module/Back-End, Status/Medium-Priority

#99 Collaboration UI Editor
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/editor/Editor.tsx
  frontend/src/components/editor/EditorTabs.tsx
  frontend/src/components/matching/Countdown.tsx
  frontend/src/components/ui/navbar/HomeNavbar.tsx
  frontend/src/components/ui/navbar/SessionNavbar.tsx
  frontend/src/constants.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/Session.tsx
Labels: Module/Front-End, Type/Feature

#103 Add Refresh Tokens
  config_env/collab-service.env.sample
  config_env/gateway.env.sample
  config_env/matching-service.env.sample
  config_env/session-service.env.sample
  gateway/src/auth/auth_agent.go
  gateway/src/auth/auth_mux.go
  gateway/src/constants.go
  gateway/src/env_loader.go
  gateway/src/main.go
  gateway/src/proto/session-service.pb.go
  proto/session-service.proto
  session-service/src/blacklist/blacklist_client.go
  session-service/src/blacklist/refresh_blacklist.go
  session-service/src/blacklist/refresh_blacklist_test.go
  session-service/src/blacklist/session_blacklist.go
  session-service/src/conn/redis_client.go
  session-service/src/consts.go
  session-service/src/env_loader.go
  session-service/src/main.go
  session-service/src/proto/session-service.pb.go
  session-service/src/service/handlers/add_blacklist_handler.go
  session-service/src/service/handlers/create_token_handler.go
  session-service/src/service/handlers/validate_token_handler.go
  session-service/src/service/session_service_server.go
  session-service/src/token/jwt_agent.go
  session-service/src/token/jwt_agent_test.go
  session-service/src/token/token_agent.go
  session-service/src/token/token_agent_test.go
  session-service/src/token/token_errors.go
  user-service/src/auth/authentication_agent.ts
  user-service/src/auth/authentication_agent_types.d.ts
  user-service/src/controller/user_bff_service_handlers/login_handler.ts
  user-service/src/controller/user_bff_service_handlers/logout_handler.ts
  user-service/src/proto/session-service.ts
  user-service/src/utils/constants.ts
Labels: Module/Back-End, Status/Medium-Priority, Type/Feature

#114 Collaboration UI - Room Status
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/editor/Editor.tsx
  frontend/src/pages/Session.tsx
  frontend/src/utils/hooks/useFixedToast.ts
  package.json
  scripts/gen-y-websocket.sh
  y-websocket/dist/src/y-websocket.d.ts
  y-websocket/dist/y-websocket.cjs
  y-websocket/dist/y-websocket.cjs.map
  y-websocket/src/y-websocket.js
Labels: Type/Feature

#116 Add Room Difficulty to Room JWT
  matching-service/src/controller/matching_service_handlers/check_status_handler.ts
  matching-service/src/redis_adapter/redis_matching_adapter.ts
  matching-service/src/room_auth/room_session_agent.ts
  matching-service/src/room_auth/room_session_agent_types.d.ts
  matchmaker/src/conn/redis_client.go
  matchmaker/src/go.mod
  matchmaker/src/go.sum
  matchmaker/src/mocks/mock_redis_client.go
  matchmaker/src/worker/match_worker.go
  matchmaker/src/worker/match_worker_test.go
Labels: Type/Enhancement, Module/Back-End, Status/High-Priority

#117 Add Redis PubSub and Question Retrieval
  collab-service/package.json
  collab-service/proto-emit.cfg
  collab-service/src/adapter/question_handler.ts
  collab-service/src/adapter/room_handler.ts
  collab-service/src/auth/authentication_agent.ts
  collab-service/src/auth/authentication_agent_types.d.ts
  collab-service/src/auth/token_blacklist.ts
  collab-service/src/controller/collab_service_controller.ts
  collab-service/src/controller/collab_service_handlers/verify_collab_handler.ts
  collab-service/src/index.ts
  collab-service/src/proto/collab-service.grpc-client.ts
  collab-service/src/proto/collab-service.grpc-server.ts
  collab-service/src/proto/collab-service.ts
  collab-service/src/proto/question-service.grpc-client.ts
  collab-service/src/proto/question-service.grpc-server.ts
  collab-service/src/proto/question-service.ts
  collab-service/src/pub_sub/collab_subscription.ts
  collab-service/src/pub_sub/collab_topic.ts
  collab-service/src/pub_sub/collab_tunnel_pubsub.ts
  collab-service/src/pub_sub/collab_tunnel_pubsub_types.d.ts
  collab-service/src/redis_adapter/redis_auth_adapter.ts
  collab-service/src/redis_adapter/redis_pubsub_adapter.ts
  collab-service/src/redis_adapter/redis_pubsub_types.d.ts
  collab-service/src/redis_adapter/redis_question_adapter.ts
  collab-service/src/room_auth/room_session_agent.ts
  collab-service/src/room_auth/room_session_agent_types.d.ts
  collab-service/src/stream_server/stream_server.ts
  collab-service/src/tunneller/collab_tunnel_redis.ts
  collab-service/src/tunneller/collab_tunnel_serializer.ts
  collab-service/src/tunneller/collab_tunnel_server.ts
  collab-service/src/utils/env_loader.ts
  config_env/collab-service.env.sample
  docker-compose.yml
  frontend/package-lock.json
  gateway/src/proto/collab-service.pb.go
  gateway/src/proto/collab-service.pb.gw.go
  gateway/src/proto/collab-service_grpc.pb.go
  proto/collab-service.proto
Labels: Module/Back-End, Type/Feature

#120 Add Disconnect Prompt
  collab-service.dockerfile
  collab-service/package-lock.json
  collab-service/package.json
  collab-service/src/api_server/api_server.ts
  collab-service/src/api_server/api_server_helpers.ts
  collab-service/src/api_server/api_server_types.d.ts
  collab-service/src/index.ts
  collab-service/src/redis_adapter/redis_pubsub_adapter.ts
  collab-service/src/redis_adapter/redis_topic_pool.ts
  collab-service/src/room/disconnect_message_builder.ts
  collab-service/src/stream_server/stream_server.ts
  collab-service/src/tunneller/collab_service_router.ts
  collab-service/src/tunneller/collab_tunnel_controller.ts
  collab-service/src/tunneller/collab_tunnel_redis.ts
  collab-service/src/tunneller/collab_tunnel_serializer.ts
  collab-service/src/utils/env_loader.ts
Labels: Type/Enhancement, Module/Back-End

#121 Add Nickname to JWT
  collab-service/src/constants.ts
  collab-service/src/index.ts
  collab-service/src/tunneller/collab_tunnel_controller.ts
  frontend/package-lock.json
  gateway/src/auth/auth_agent.go
  gateway/src/auth/auth_constants.go
  gateway/src/auth/auth_mux.go
  gateway/src/constants.go
  gateway/src/middleware_proxy.go
  gateway/src/proto/session-service.pb.go
  gateway/src/proxy/grpc_proxy_client.go
  gateway/src/proxy/proxy_constants.go
  proto/session-service.proto
  session-service/src/constants.go
  session-service/src/proto/session-service.pb.go
  session-service/src/service/handlers/create_token_handler.go
  session-service/src/service/handlers/validate_token_handler.go
  session-service/src/token/token.go
  user-service/src/auth/authentication_agent.ts
  user-service/src/auth/authentication_agent_types.d.ts
  user-service/src/constants.ts
  user-service/src/controller/user_bff_service_handlers/login_handler.ts
  user-service/src/index.ts
  user-service/src/proto/session-service.ts
Labels: Type/Enhancement, Module/Back-End

#129 Disconnect Integration
  frontend/src/App.tsx
  frontend/src/app/store.ts
  frontend/src/components/modal/DisconnectModal.tsx
  frontend/src/components/modal/LeaveModal.tsx
  frontend/src/components/ui/navbar/HomeNavbar.tsx
  frontend/src/feature/user/userSlice.ts
  frontend/src/pages/Session.tsx
Labels: Module/Front-End
